### ISSUE TITLE
擋掉男人幫網站蓋板廣告會導致無法向下捲動

### ISSUE THREAD

**Issue by oobe** [ethanhuang13/blahker#125]
在 Mac Safari 下：http://www.fhm.com.tw/

**Comment by ethanhuang13** [comment]
Hello,

好，我有空看看

**Comment by oobe** [comment]
Cool!

**Comment by ethanhuang13** [comment]
研究之後發現它的捲動是寫死在主畫面，
沒辦法同時做到拿掉廣告又維持捲動，
所以只好把這個網站的擋廣告拿掉了 ._. （已更新）

最好的方法是跟網站反映，請他們不要用蓋版廣告
