### ISSUE TITLE
facebook貼文無法載入

### ISSUE THREAD

**Issue by JamesMatt** [ethanhuang13/blahker#155]
我把blahker的規則 (https://raw.githubusercontent.com/ethanhuang13/blahker/master/Blahker.safariextension/blockerList.json) 加到uBlock去阻擋廣告，但facebook的動態牆卻沒辦法載入貼文

錄影畫面：http://d.pr/v/PkV1JX

**Comment by ethanhuang13** [comment]
uBlock不是使用Safari Content Blocker的API，當然不會有用
