### ISSUE TITLE
蘋果日報的蓋板廣告仍然存在

### ISSUE THREAD

**Issue by JamesMatt** [ethanhuang13/blahker#156]
![screenshot 2017-07-15 1 11 03](https://user-images.githubusercontent.com/25457860/28236972-18d83b6a-6967-11e7-9420-b852ec9bf5e2.jpg)

我把阻擋規則加到uBlock，還是看得到蘋果日報的蓋版網告
[http://www.appledaily.com.tw/realtimenews/article/international/20170715/1161596/1](url)

**Comment by ethanhuang13** [comment]
uBlock不是使用Safari Content Blocker的API，當然不會有用
