### ISSUE TITLE
Add bnext.com.tw

### ISSUE THREAD

**Issue by hansbobby** [ethanhuang13/blahker#73]
Sample: http://www.bnext.com.tw/article/42411

**Comment by ethanhuang13** [comment]
Thanks for the submission. Please attach screenshot, too.

**Comment by hansbobby** [comment]
<img width="458" alt="bnext" src="https://cloud.githubusercontent.com/assets/1186486/21490421/565d4d02-cc2f-11e6-8cb4-1a4489dc0db1.png">
