### ISSUE TITLE
Update sina.com.tw

### ISSUE THREAD

**Issue by ethanhuang13** [ethanhuang13/blahker#92]

**Comment by ethanhuang13** [comment]
![img_0565](https://cloud.githubusercontent.com/assets/12409307/21562273/b2251eb4-ceb2-11e6-9a57-d24dd20deb5b.PNG)
![img_0566](https://cloud.githubusercontent.com/assets/12409307/21562274/b272355a-ceb2-11e6-9088-ecbed7f43778.PNG)

**Comment by ethanhuang13** [comment]
I still need to check this one.

**Comment by hansbobby** [comment]
After checking the screenshot, what 0ee8fec blocks is another overlay ad.
I'll add a rule for this.

**Comment by ethanhuang13** [comment]
There is another div.mfp-wrap. Added in 7d2e7f2

**Comment by ethanhuang13** [comment]
Verified

**Comment by hansbobby** [comment]
How do you test the rules before committing changes?
The iOS app can only download committed rule (json file) from github, right?

**Comment by ethanhuang13** [comment]
I use the Mac Safari Extension Builder to verify the format. If you have an Apple developer account, you can try it. See [here](https://github.com/krishkumar/BlockParty/blob/master/BlockParty%20-%20Desktop%20Safari/How%20to%20Install.md).

I can also build the app with the json file included. But most of the time I just check the format and push it to GitHub, and verify the result later on my phone.

I'm thinking to build a CI system to verify the format automatically #91 . But, the format is verified by Safari, after all, therefore the unit tests result won't be perfectly match. We still need to verify with the Extension Builder.

**Comment by hansbobby** [comment]
Okay. So there are two verifications: 1. authenticity of json format; 2. effectiveness of rules.

For item 1 we can use Extension Builder or CI system (#91); for item 2 we now only verify on phones after checking in rules. Is that correct?

**Comment by ethanhuang13** [comment]
Correct.

**Comment by hansbobby** [comment]
Roger that. I was thinking if there's a way to verify 2. rule effectiveness before checking code in. I'll directly commit new rules then.

**Comment by ethanhuang13** [comment]
I'll make a debug mode in the app #97 for this later.
