### ISSUE TITLE
Add SF overlay ad

### ISSUE THREAD

**Issue by hansbobby** [ethanhuang13/blahker#96]
Sample: http://www.christabelle.idv.tw/archives/3094

![852107321_15733465376984960167](https://cloud.githubusercontent.com/assets/1186486/21612025/58f69f88-d20a-11e6-960b-96ffefd77308.jpg)

**Comment by hansbobby** [comment]
Using third-party script to add overlay. I'll block the scripts directly.

**Comment by ethanhuang13** [comment]
OK

**Comment by ethanhuang13** [comment]
I merge the PR, but it seems like there is still a div#sf_popup to block. @hansbobby

**Comment by hansbobby** [comment]
Okay. Let me check on that later today. Where was it seen? On iPad or on iPhone?

**Comment by ethanhuang13** [comment]
![img_0590](https://cloud.githubusercontent.com/assets/12409307/21667440/157756b4-d334-11e6-85a1-810b493a75bb.PNG)

iPhone

**Comment by ethanhuang13** [comment]
@hansbobby Hi, still working on this one?

**Comment by hansbobby** [comment]
Hi @EthanHuang13,

Happy new year.
Sorry I was too busy recently. Also it seems that I cannot build the Xcode project.
I'll need some time to try on the debug mode. Maybe after the Lunar New Year.

<img width="279" alt="xcode_build_fail" src="https://cloud.githubusercontent.com/assets/1186486/22359509/c16c62ca-e482-11e6-8313-324fb788f8f5.png">

**Comment by hansbobby** [comment]
Oh, wait. It looks like I'll need CocoaPods. I'll try that later.

**Comment by ethanhuang13** [comment]
@hansbobby I've block sfpdpopexp.js for all domain. Close the issue
